### PR TITLE
docs: conventional commits

### PR DESCRIPTION
**Pull request by dn-l**
[Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
A specification for adding human and machine readable meaning to commit messages

### CODE REVIEW

**Comment by Alex-Werner** [comment]
@antouhou : Does this solve your requirements of having validation on squashing too ? (added validation of title too)

cc : @denlb

**Comment by Alex-Werner** [comment]
@shumkov It's `conventional` types. They are used with other plugins in order to, for instance, auto-gen a changelog (as you can see an example on NodeJS https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V012.md#0.12.14). 

The types are : 



 ```
"feat": {
      "description": "A new feature",
      "title": "Features"
    },
    "fix": {
      "description": "A bug fix",
      "title": "Bug Fixes"
    },
    "improvement": {
      "description": "An improvement to a current feature",
      "title": "Improvements"
    },
    "docs": {
      "description": "Documentation only changes",
      "title": "Documentation"
    },
    "style": {
      "description": "Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)",
      "title": "Styles"
    },
    "refactor": {
      "description": "A code change that neither fixes a bug nor adds a feature",
      "title": "Code Refactoring"
    },
    "perf": {
      "description": "A code change that improves performance",
      "title": "Performance Improvements"
    },
    "test": {
      "description": "Adding missing tests or correcting existing tests",
      "title": "Tests"
    },
    "build": {
      "description": "Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)",
      "title": "Builds"
    },
    "ci": {
      "description": "Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)",
      "title": "Continuous Integrations"
    },
    "chore": {
      "description": "Other changes that don't modify src or test files",
      "title": "Chores"
    },
    "revert": {
      "description": "Reverts a previous commit",
      "title": "Reverts"
    }
```

**Comment by denlb** [comment]
@shumkov @Alex-Werner we can use any other convention (task types) just tell me which one.
Scope is just string, could be anything.

**Comment by thephez** [comment]
Is there a reason this is still unmerged? Having a convention without defined scopes is better than having no convention at all.

**Comment by antouhou** [comment]
@thephez This one can't be merged until @shumkov removes his rejecting comment

**Comment by dn-l** [comment]
Closed as outdated

**Pull request closed without merging**
