### PR TITLE
feat: convenient response errors

### PR DESCRIPTION
**Pull request by shumkov**
## Issue being fixed or feature implemented

To allow SDK and applications handle different errors and get comprehensive information about them, we need to break ResponseError into different classes and read error data from DAPI

## What was done?

- Introduce `TimeoutError`, `InvalidRequestError`, `InvalidRequestDPPError`, `ServerError`
- `MaxRetriesReachedError` and `NoAvailableAddressesForRetryError` now contains cause error
- Read error data from gRPC metadata

## How Has This Been Tested?

With tests

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by jawid-h — DISMISSED** [review]
Looks legit!

**Comment by Alex-Werner** [comment]
Test is breaking, but looking really good ! Nice job

**Comment by shumkov** [comment]
@Alex-Werner what test? ))

**Review by Alex-Werner — DISMISSED** [review]
Great job!

**Review by strophy — APPROVED** [review]
:+1:

**Review by Alex-Werner — APPROVED** [review]

**Pull request merged**
